SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SHOW columns FROM producto;
SELECT nombre, CONCAT(precio, "€"), CONCAT(precio, "$") FROM producto;
SELECT nombre, CONCAT(precio, "€") AS Euros, CONCAT(precio, "$") AS USD FROM producto;
SELECT UPPER(nombre), precio FROM producto;
SELECT LOWER(nombre), precio FROM producto;
SELECT nombre, UPPER(SUBSTRING(nombre,1,2)) AS Iniciales FROM fabricante;
SELECT nombre, precio, ROUND(precio,0) AS Arrodoniment FROM producto;
SELECT nombre, precio, ROUND(precio,0,1) AS Truncat FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT DISTINCT codigo_fabricante FROM producto;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 3 OFFSET 3;
SELECT nombre, precio FROM producto ORDER BY PRECIO ASC LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY PRECIO DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante=2;
SELECT producto.nombre AS Nombre_Producto, precio, fabricante.nombre AS Nombre_Fabricante FROM producto, fabricante;
SELECT producto.nombre AS Nombre_Producto, precio, fabricante.nombre AS Nombre_Fabricante FROM producto, fabricante ORDER BY fabricante.nombre;
SELECT producto.codigo, producto.nombre, fabricante.codigo, fabricante.nombre FROM producto, fabricante;
SELECT producto.nombre, precio, fabricante.nombre FROM producto, fabricante ORDER BY precio ASC LIMIT 1;
SELECT producto.nombre, precio, fabricante.nombre FROM producto, fabricante ORDER BY precio DESC LIMIT 1;
SELECT producto.nombre, fabricante.nombre FROM producto, fabricante WHERE fabricante.nombre ="Lenovo";
SELECT producto.nombre, fabricante.nombre, precio FROM producto, fabricante WHERE fabricante.nombre ="Crucial" AND precio>200;
SELECT producto.nombre, fabricante.nombre FROM producto, fabricante WHERE fabricante.nombre ="Asus" OR fabricante.nombre ="Hewlett-Packard" OR fabricante.nombre ="Seagate";
SELECT producto.nombre, fabricante.nombre FROM producto, fabricante WHERE fabricante.nombre IN ("Asus", "Hewlett-Packard", "Seagate");
SELECT producto.nombre, precio, fabricante.nombre FROM producto, fabricante WHERE fabricante.nombre LIKE "%e";
SELECT producto.nombre, precio, fabricante.nombre FROM producto, fabricante WHERE fabricante.nombre LIKE "%w%";
SELECT producto.nombre, precio, fabricante.nombre FROM producto, fabricante WHERE precio>=180 ORDER BY precio ASC, producto.nombre DESC;
SELECT fabricante.codigo, fabricante.nombre FROM producto, fabricante WHERE fabricante.codigo=codigo_fabricante;
SELECT fabricante.nombre, producto.nombre FROM producto, fabricante WHERE fabricante.codigo IS NULL OR fabricante.codigo IS NOT NULL ;
SELECT DISTINCT fabricante.nombre, fabricante.codigo FROM fabricante INNER JOIN producto ON fabricante.codigo!=codigo_fabricante;
SELECT producto.nombre, fabricante.nombre FROM producto, fabricante WHERE fabricante.nombre="Lenovo";
SELECT * FROM producto, fabricante WHERE precio= (SELECT MAX(precio) FROM producto, fabricante WHERE fabricante.nombre = "Lenovo");
SELECT producto.nombre, fabricante.nombre, precio FROM producto, fabricante WHERE fabricante.nombre="Lenovo" AND precio = (SELECT MAX(precio) FROM producto) ;
SELECT producto.nombre, fabricante.nombre, precio FROM producto, fabricante WHERE fabricante.nombre="Hewlett-Packard" AND precio= (SELECT MIN(precio) FROM producto);
SELECT nombre, precio FROM producto WHERE precio>=(SELECT MAX(precio) FROM fabricante INNER JOIN producto ON fabricante.nombre = "Lenovo");
SELECT nombre, precio FROM producto WHERE precio>(SELECT AVG(precio) FROM fabricante INNER JOIN producto ON fabricante.nombre="Asus");


